"""user-entity

Revision ID: fa17ebbe2192
Revises: 15770e820938
Create Date: 2022-08-26 20:18:50.700242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa17ebbe2192'
down_revision = '15770e820938'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
